// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/12/2026, 4:30:41 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/plugins/**/*.{js,ts,mjs}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/composables/**/*.{js,ts,mjs}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/utils/**/*.{js,ts,mjs}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/pc-yaran/Desktop/programmig/nader-tech/rahe-abrisham/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;